import { School } from '../types';

const s = (name: string, nameJa: string, gender: 'M' | 'W' | 'Both' = 'Both') => ({ name, nameJa, gender });

// SAMPLE SEED DATA — verified:false means check official sites before relying on it.
// Full dataset is generated by `npm run build:data` (see scripts/build-data.mjs).
const sample: School[] = [
  {
    id: 'ucla', name: 'University of California, Los Angeles', nameJa: 'カリフォルニア大学ロサンゼルス校',
    level: '4year', control: 'public', city: 'Los Angeles', state: 'CA', association: 'NCAA', division: 'D1',
    conference: 'Big Ten', sports: [s('Baseball', '野球', 'M'), s('Soccer', 'サッカー'), s('Tennis', 'テニス'), s('Swimming', '水泳')],
    tuitionInState: null, tuitionOutOfState: null, athleticScholarship: true,
    scholarshipNote: '留学生もアスリート奨学金の対象になり得ます(競技・学年による)', website: 'https://www.ucla.edu', verified: false,
  },
  {
    id: 'stanford', name: 'Stanford University', nameJa: 'スタンフォード大学',
    level: '4year', control: 'private', city: 'Stanford', state: 'CA', association: 'NCAA', division: 'D1',
    conference: 'ACC', sports: [s('Baseball', '野球', 'M'), s('Tennis', 'テニス'), s('Swimming', '水泳'), s('Golf', 'ゴルフ')],
    tuitionInState: null, tuitionOutOfState: null, athleticScholarship: true, website: 'https://www.stanford.edu', verified: false,
  },
  {
    id: 'hpu', name: 'Hawaii Pacific University', nameJa: 'ハワイパシフィック大学',
    level: '4year', control: 'private', city: 'Honolulu', state: 'HI', association: 'NCAA', division: 'D2',
    sports: [s('Soccer', 'サッカー'), s('Tennis', 'テニス'), s('Swimming', '水泳')],
    tuitionInState: null, tuitionOutOfState: null, athleticScholarship: true, website: 'https://www.hpu.edu', verified: false,
  },
  {
    id: 'cal-lutheran', name: 'California Lutheran University', nameJa: 'カリフォルニア・ルーセラン大学',
    level: '4year', control: 'private', city: 'Thousand Oaks', state: 'CA', association: 'NCAA', division: 'D3',
    sports: [s('Baseball', '野球', 'M'), s('Soccer', 'サッカー'), s('Tennis', 'テニス')],
    tuitionInState: null, tuitionOutOfState: null, athleticScholarship: false,
    scholarshipNote: 'D3はアスリート奨学金なし(学業・ニーズ型の奨学金のみ)', website: 'https://www.callutheran.edu', verified: false,
  },
  {
    id: 'smc', name: 'Santa Monica College', nameJa: 'サンタモニカ・カレッジ',
    level: '2year', control: 'public', city: 'Santa Monica', state: 'CA', association: 'CCCAA', division: 'CCCAA',
    sports: [s('Baseball', '野球', 'M'), s('Soccer', 'サッカー'), s('Swimming', '水泳')],
    tuitionInState: null, tuitionOutOfState: null, athleticScholarship: false,
    scholarshipNote: 'CCCAAは原則アスリート奨学金なし', website: 'https://www.smc.edu', verified: false,
  },
  {
    id: 'hutchinson', name: 'Hutchinson Community College', nameJa: 'ハッチンソン・コミュニティカレッジ',
    level: '2year', control: 'public', city: 'Hutchinson', state: 'KS', association: 'NJCAA', division: 'NJCAA-D1',
    sports: [s('Baseball', '野球', 'M'), s('Basketball', 'バスケットボール'), s('Football', 'フットボール', 'M')],
    tuitionInState: null, tuitionOutOfState: null, athleticScholarship: true, website: 'https://www.hutchcc.edu', verified: false,
  },
];

import generated from './schools.generated.json';
// Full list (NCAA via `npm run fetch:ncaa && npm run build:data`); falls back to the sample if empty.
export const schools: School[] = (generated as unknown as School[]).length ? (generated as unknown as School[]) : sample;
